### ISSUE TITLE
Would be great if it had client-only version too

### ISSUE THREAD

**Issue by baturinsky** [dgurkaynak/chess-ai#1]
I was searching for good js chess ai, could not find anything decent. Your AI looks great, but I needed something that would work in browser.

**Comment by dgurkaynak** [comment]
All the AI part is pure javascript, you can easily port it by using webworkers. I may look into it when I have available time.

**Comment by dgurkaynak** [comment]
Hey @baturinsky, I've refactored the whole repo, dropped node.js usage and migrated to web workers, as I told you. Thanks for the recommendation by the way, the repo is much more clean now 😄And since there is no backend to maintain, I've just deployed it to my VPS, which is available on [https://deniz.co/chess-ai/](https://deniz.co/chess-ai/).
